In [1]:
import sklearn
import pandas as pd
import numpy as np
import warnings

import matplotlib.pyplot as plt

In [2]:
games = pd.read_csv('./games.csv', ';')
#print(games.head(5))
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50286 entries, 0 to 50285
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gameDuration        50286 non-null  int64
 1   firstBlood          50286 non-null  int64
 2   firstTower          50286 non-null  int64
 3   firstInhibitor      50286 non-null  int64
 4   firstBaron          50286 non-null  int64
 5   firstDragon         50286 non-null  int64
 6   firstRiftHerald     50286 non-null  int64
 7   t1_towerKills       50286 non-null  int64
 8   t1_inhibitorKills   50286 non-null  int64
 9   t1_baronKills       50286 non-null  int64
 10  t1_dragonKills      50286 non-null  int64
 11  t1_riftHeraldKills  50286 non-null  int64
 12  t2_towerKills       50286 non-null  int64
 13  t2_inhibitorKills   50286 non-null  int64
 14  t2_baronKills       50286 non-null  int64
 15  t2_dragonKills      50286 non-null  int64
 16  t2_riftHeraldKills  50286 non-null  int6

/home/diegoflm/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3369: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
# Variables cuantitativas (tipo entero)
games.select_dtypes(include=['int64']).describe()

gameDuration    firstBlood    firstTower  firstInhibitor    firstBaron  \
count  50286.000000  50286.000000  50286.000000    50286.000000  50286.000000   
mean    1871.386032      1.487233      1.485125        1.339578      0.948693   
std      450.876052      0.499842      0.500499        0.652960      0.838988   
min      610.000000      1.000000      0.000000        0.000000      0.000000   
25%     1554.000000      1.000000      1.000000        1.000000      0.000000   
50%     1846.000000      1.000000      1.000000        1.000000      1.000000   
75%     2156.750000      2.000000      2.000000        2.000000      2.000000   
max     4728.000000      2.000000      2.000000        2.000000      2.000000   

        firstDragon  firstRiftHerald  t1_towerKills  t1_inhibitorKills  \
count  50286.000000     50286.000000   50286.000000       50286.000000   
mean       1.477270         0.749195       5.835163           1.041781   
std        0.530346         0.824393       3.740575           1.269064   
min        0.000000         0.000000       0.000000           0.000000   
25%        1.000000         0.000000       2.000000           0.000000   
50%        1.000000         1.000000       6.000000           1.000000   
75%        2.000000         1.000000       9.000000           2.000000   
max        2.000000         2.000000      11.000000          10.000000   

       t1_baronKills  t1_dragonKills  t1_riftHeraldKills  t2_towerKills  \
count   50286.000000    50286.000000        50286.000000   50286.000000   
mean        0.381200        1.420356            0.257487       5.681999   
std         0.588001        1.201740            0.437254       3.809336   
min         0.000000        0.000000            0.000000       0.000000   
25%         0.000000        0.000000            0.000000       2.000000   
50%         0.000000        1.000000            0.000000       6.000000   
75%         1.000000        2.000000            1.000000       9.000000   
max         5.000000        6.000000            1.000000      11.000000   

       t2_inhibitorKills  t2_baronKills  t2_dragonKills  t2_riftHeraldKills  \
count       50286.000000   50286.000000    50286.000000        50286.000000   
mean            1.008611       0.424472        1.437975            0.245854   
std             1.261867       0.617672        1.219412            0.430597   
min             0.000000       0.000000        0.000000            0.000000   
25%             0.000000       0.000000        0.000000            0.000000   
50%             0.000000       0.000000        1.000000            0.000000   
75%             2.000000       1.000000        2.000000            0.000000   
max            10.000000       4.000000        6.000000            1.000000   

             winner  
count  50286.000000  
mean       1.493776  
std        0.499966  
min        1.000000  
25%        1.000000  
50%        1.000000  
75%        2.000000  
max        2.000000

# Split training data from test data.

In [4]:
from sklearn.model_selection import train_test_split
N=len(games)
cTrain=int(N*0.8) # 80% para entrenar y 20% para probar
cTest=N-cTrain
print(N,cTrain,cTest)
train_data, test_data = sklearn.model_selection.train_test_split(games, train_size=cTrain, test_size=cTest)

50286 40228 10058


In [5]:
#train_data.shape
train_data.head()

gameDuration  firstBlood  firstTower  firstInhibitor  firstBaron  \
39803          1907           1           1               1           0   
8173           2055           1           1               2           0   
3463           2329           2           2               2           2   
4311           1241           1           2               2           0   
46497          1258           2           1               0           0   

       firstDragon  firstRiftHerald  t1_towerKills  t1_inhibitorKills  \
39803            1                0              9                  1   
8173             2                0              6                  0   
3463             2                2              4                  0   
4311             2                0              0                  0   
46497            1                0              3                  0   

       t1_baronKills  t1_dragonKills  t1_riftHeraldKills  t2_towerKills  \
39803              0               1                   0              2   
8173               0               2                   0             10   
3463               0               1                   0              9   
4311               0               0                   0              8   
46497              0               1                   0              1   

       t2_inhibitorKills  t2_baronKills  t2_dragonKills  t2_riftHeraldKills  \
39803                  0              0               2                   0   
8173                   2              0               2                   0   
3463                   1              2               3                   1   
4311                   2              0               2                   0   
46497                  0              0               0                   0   

       winner  
39803       1  
8173        2  
3463        2  
4311        2  
46497       1

# Pipeline for categorical attributes

In [6]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [7]:
#6 categorical attributes
cat_atts = ['firstBlood','firstTower', 'firstInhibitor', 'firstBaron', 'firstDragon', 'firstRiftHerald']
cat_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("cat_encoder", OneHotEncoder(sparse=False))
    ])

# Pipeline for numeric attributes

In [8]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [9]:
#11 numeric attributes
num_atts = ['gameDuration', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills', 't1_dragonKills', 
        't1_riftHeraldKills', 't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills', 
        't2_riftHeraldKills']

num_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()) 
    ])

# Pipeline completo

In [10]:
from sklearn.compose import ColumnTransformer

full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_atts),
    ("cat", cat_pipeline, cat_atts), 
])

In [11]:
X_train = full_pipeline.fit_transform(train_data)

In [12]:
X_train.shape

(40228, 28)

In [13]:
X_train[0,:]

array([ 0.07864796,  0.84451494, -0.03465914, -0.64885115, -0.34940022,
       -0.58825872, -0.96503923, -0.79885364, -0.6866721 ,  0.46076727,
       -0.57076729,  1.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        1.        ,  0.        ,  0.        ])

In [14]:
y_train = train_data["winner"]
y_train

39803    1
8173     2
3463     2
4311     2
46497    1
        ..
23866    2
45969    2
32874    2
7288     2
8919     1
Name: winner, Length: 40228, dtype: int64

# Neuronal network training

In [15]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score

In [16]:
model1 = MLPClassifier(activation='identity',solver='lbfgs', alpha=1e-5,
    hidden_layer_sizes=(4,7), random_state=123)

model1.fit(X_train, y_train)
scores1 = cross_val_score(model1, X_train, y_train, cv=5, scoring='neg_mean_absolute_error')
print(scores1)
scores1.mean()

[-0.02771564 -0.02572707 -0.02846135 -0.02461156 -0.02647607]


-0.026598336754463575

# On the test set:

In [17]:
X_test = full_pipeline.transform(test_data)
X_test

array([[-0.42950871,  0.57711722,  0.75440025, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.41593971, -1.02726906, -0.82371854, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.35380702, -1.56206448, -0.82371854, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [-1.33265177, -1.56206448, -0.82371854, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.40928264,  0.84451494, -0.03465914, ...,  0.        ,
         1.        ,  0.        ],
       [-0.80674291,  0.57711722, -0.03465914, ...,  0.        ,
         1.        ,  0.        ]])

In [18]:
y_pred1 = model1.predict(X_test)  
y_pred1

array([1, 2, 2, ..., 2, 1, 1])

In [19]:
y_test = test_data["winner"]

In [20]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(
        y_true  = y_test,
        y_pred  = y_pred1
       )
print(f"El error medio absoluto del modelo 1 es: {mae}")

El error medio absoluto del modelo 1 es: 0.02783853648836747


In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred1)

0.9721614635116326

In [22]:
from sklearn.metrics import confusion_matrix

confusion_matrix1 = confusion_matrix(y_test, y_pred1)
confusion_matrix1

array([[4917,  147],
       [ 133, 4861]])