In [3]:
import sklearn
import pandas as pd
import numpy as np
import warnings

import matplotlib.pyplot as plt

In [4]:
games = pd.read_csv('./games.csv', ';')
#print(games.head(5))
games.info()

/home/diegoflm/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3369: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  exec(code_obj, self.user_global_ns, self.user_ns)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50286 entries, 0 to 50285
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gameDuration        50286 non-null  int64
 1   firstBlood          50286 non-null  int64
 2   firstTower          50286 non-null  int64
 3   firstInhibitor      50286 non-null  int64
 4   firstBaron          50286 non-null  int64
 5   firstDragon         50286 non-null  int64
 6   firstRiftHerald     50286 non-null  int64
 7   t1_towerKills       50286 non-null  int64
 8   t1_inhibitorKills   50286 non-null  int64
 9   t1_baronKills       50286 non-null  int64
 10  t1_dragonKills      50286 non-null  int64
 11  t1_riftHeraldKills  50286 non-null  int64
 12  t2_towerKills       50286 non-null  int64
 13  t2_inhibitorKills   50286 non-null  int64
 14  t2_baronKills       50286 non-null  int64
 15  t2_dragonKills      50286 non-null  int64
 16  t2_riftHeraldKills  50286 non-null  int6

In [5]:
# Variables cuantitativas (tipo entero)
games.select_dtypes(include=['int64']).describe()

gameDuration    firstBlood    firstTower  firstInhibitor    firstBaron  \
count  50286.000000  50286.000000  50286.000000    50286.000000  50286.000000   
mean    1871.386032      1.487233      1.485125        1.339578      0.948693   
std      450.876052      0.499842      0.500499        0.652960      0.838988   
min      610.000000      1.000000      0.000000        0.000000      0.000000   
25%     1554.000000      1.000000      1.000000        1.000000      0.000000   
50%     1846.000000      1.000000      1.000000        1.000000      1.000000   
75%     2156.750000      2.000000      2.000000        2.000000      2.000000   
max     4728.000000      2.000000      2.000000        2.000000      2.000000   

        firstDragon  firstRiftHerald  t1_towerKills  t1_inhibitorKills  \
count  50286.000000     50286.000000   50286.000000       50286.000000   
mean       1.477270         0.749195       5.835163           1.041781   
std        0.530346         0.824393       3.740575           1.269064   
min        0.000000         0.000000       0.000000           0.000000   
25%        1.000000         0.000000       2.000000           0.000000   
50%        1.000000         1.000000       6.000000           1.000000   
75%        2.000000         1.000000       9.000000           2.000000   
max        2.000000         2.000000      11.000000          10.000000   

       t1_baronKills  t1_dragonKills  t1_riftHeraldKills  t2_towerKills  \
count   50286.000000    50286.000000        50286.000000   50286.000000   
mean        0.381200        1.420356            0.257487       5.681999   
std         0.588001        1.201740            0.437254       3.809336   
min         0.000000        0.000000            0.000000       0.000000   
25%         0.000000        0.000000            0.000000       2.000000   
50%         0.000000        1.000000            0.000000       6.000000   
75%         1.000000        2.000000            1.000000       9.000000   
max         5.000000        6.000000            1.000000      11.000000   

       t2_inhibitorKills  t2_baronKills  t2_dragonKills  t2_riftHeraldKills  \
count       50286.000000   50286.000000    50286.000000        50286.000000   
mean            1.008611       0.424472        1.437975            0.245854   
std             1.261867       0.617672        1.219412            0.430597   
min             0.000000       0.000000        0.000000            0.000000   
25%             0.000000       0.000000        0.000000            0.000000   
50%             0.000000       0.000000        1.000000            0.000000   
75%             2.000000       1.000000        2.000000            0.000000   
max            10.000000       4.000000        6.000000            1.000000   

             winner  
count  50286.000000  
mean       1.493776  
std        0.499966  
min        1.000000  
25%        1.000000  
50%        1.000000  
75%        2.000000  
max        2.000000

# Split training data from test data: 80% for training, 20% for testing.

In [6]:
from sklearn.model_selection import train_test_split
N=len(games)
cTrain=int(N*0.8) # 80% for training and 20% for testing
cTest=N-cTrain
print(N,cTrain,cTest)
train_data, test_data = sklearn.model_selection.train_test_split(games, train_size=cTrain, test_size=cTest)

50286 40228 10058


In [7]:
#train_data.shape
train_data.head()

gameDuration  firstBlood  firstTower  firstInhibitor  firstBaron  \
45072          1852           2           2               2           2   
42967          2532           1           2               1           1   
3474           1807           1           1               1           1   
35837          2027           1           1               1           1   
36969          2030           2           2               2           0   

       firstDragon  firstRiftHerald  t1_towerKills  t1_inhibitorKills  \
45072            2                0              2                  0   
42967            1                0             11                  3   
3474             1                1             10                  2   
35837            1                0             11                  4   
36969            2                0              2                  0   

       t1_baronKills  t1_dragonKills  t1_riftHeraldKills  t2_towerKills  \
45072              0               0                   0             10   
42967              1               4                   0              6   
3474               1               2                   1              1   
35837              1               3                   0              0   
36969              0               1                   0             11   

       t2_inhibitorKills  t2_baronKills  t2_dragonKills  t2_riftHeraldKills  \
45072                  2              1               2                   0   
42967                  0              0               1                   0   
3474                   0              0               1                   0   
35837                  0              0               0                   0   
36969                  4              0               3                   0   

       winner  
45072       2  
42967       1  
3474        1  
35837       1  
36969       2

# Pipeline for categorical attributes

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [9]:
#6 categorical attributes, where the numeric values don't have a numerical meaning.
cat_atts = ['firstBlood','firstTower', 'firstInhibitor', 'firstBaron', 'firstDragon', 'firstRiftHerald']
cat_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("cat_encoder", OneHotEncoder(sparse=False))
    ])

# Pipeline for numeric attributes

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [11]:
#11 numeric attributes
num_atts = ['gameDuration', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills', 't1_dragonKills', 
        't1_riftHeraldKills', 't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills', 
        't2_riftHeraldKills']

num_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())    #Standarization by centering and scaling.
    ])

# Pipeline completo

In [12]:
from sklearn.compose import ColumnTransformer

full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_atts),
    ("cat", cat_pipeline, cat_atts), 
])

In [13]:
X_train = full_pipeline.fit_transform(train_data)

In [14]:
X_train.shape

(40228, 28)

In [15]:
X_train[0,:]

array([-0.04491115, -1.02503239, -0.82061401, -0.64834784, -1.18124104,
       -0.58772277,  1.13154481,  0.7858743 ,  0.93043267,  0.46169807,
       -0.57007832,  0.        ,  1.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
        1.        ,  0.        ,  0.        ])

In [16]:
y_train = train_data["winner"]
y_train

45072    2
42967    1
3474     1
35837    1
36969    2
        ..
16618    1
21087    1
36669    1
15883    2
45275    2
Name: winner, Length: 40228, dtype: int64

# Neuronal network training models

In [17]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score

In [18]:
model1 = MLPClassifier(activation='identity',solver='lbfgs', alpha=1e-5,
    hidden_layer_sizes=(4,7), random_state=123)

model1.fit(X_train, y_train)
scores1 = cross_val_score(model1, X_train, y_train, cv=5, scoring='neg_mean_absolute_error')
print(scores1)
scores1.mean()

[-0.02995277 -0.02846135 -0.02522993 -0.02834058 -0.02573027]


-0.027542979638365904

In [19]:
modelo2 = MLPClassifier(activation='relu',solver='sgd', alpha=1e-5,hidden_layer_sizes=(3, 3, 3, 3), random_state=123)
modelo2.fit(X_train, y_train)
scores2 = cross_val_score(modelo2, X_train, y_train, cv=5, scoring='neg_mean_absolute_error')
print(scores2)
scores2.mean()

/home/diegoflm/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/diegoflm/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/diegoflm/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/diegoflm/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/diegoflm/anaconda3/lib/pyt

[-0.02622421 -0.02560278 -0.0212528  -0.02523306 -0.02486016]


/home/diegoflm/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


-0.024634603361312603

In [87]:
model3 = MLPClassifier(activation='tanh',solver='adam', alpha=1e-5,hidden_layer_sizes=(5, 5, 5, 5, 5), random_state=123)
model3.fit(X_train, y_train)
scores3 = cross_val_score(model3, X_train, y_train, cv=5, scoring='neg_mean_absolute_error')
print(scores3)
scores3.mean()

[-0.02286851 -0.02063137 -0.01851852 -0.02088254 -0.01988813]


-0.020557811848496376

In [88]:
model4 = MLPClassifier(activation='tanh',solver='adam', alpha=1e-5,hidden_layer_sizes=(4, 10, 3), random_state=123)
model4.fit(X_train, y_train)
scores4 = cross_val_score(model4, X_train, y_train, cv=5, scoring='neg_mean_absolute_error')
print(scores4)
scores4.mean()

[-0.02249565 -0.02137708 -0.01913995 -0.02026103 -0.02311995]


-0.021278731816603936

In [112]:
model5 = MLPClassifier(activation='tanh',solver='sgd', alpha=1e-5,hidden_layer_sizes=(1), random_state=123)
model5.fit(X_train, y_train)
scores5 = cross_val_score(model5, X_train, y_train, cv=5, scoring='neg_mean_absolute_error')
print(scores5)
scores5.mean()

[-0.03032563 -0.02796421 -0.02448422 -0.02759478 -0.02597887]


-0.027269539489143145

# On the test set:

In [113]:
X_test = full_pipeline.transform(test_data)
X_test

array([[-1.41652526, -1.29256979, -0.82061401, ...,  1.        ,
         0.        ,  0.        ],
       [-0.70195855, -1.56010718, -0.82061401, ...,  1.        ,
         0.        ,  0.        ],
       [-2.58682181,  0.58019196, -0.0333287 , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 0.55461695, -1.02503239, -0.82061401, ...,  1.        ,
         0.        ,  0.        ],
       [-0.34578134,  1.11526674,  0.75395662, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.45063976,  1.38280413,  1.54124193, ...,  0.        ,
         1.        ,  0.        ]])

In [114]:
y_pred1 = model1.predict(X_test)  
y_pred1

array([2, 2, 1, ..., 2, 1, 1])

In [115]:
y_pred2 = modelo2.predict(X_test)  
y_pred2

array([2, 2, 1, ..., 2, 1, 1])

In [116]:
y_pred3 = model3.predict(X_test)  
y_pred3

array([1, 2, 1, ..., 2, 1, 1])

In [117]:
y_pred4 = model4.predict(X_test)  
y_pred4

array([1, 2, 1, ..., 2, 1, 1])

In [118]:
y_pred5 = model5.predict(X_test)  
y_pred5

array([2, 2, 1, ..., 2, 1, 1])

In [119]:
y_test = test_data["winner"]

# Results

In [120]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(
        y_true  = y_test,
        y_pred  = y_pred1
       )
print(f"Mean Absolute Error for model1: {mae}")

Mean Absolute Error for model1: 0.02545237621793597


In [121]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(
        y_true  = y_test,
        y_pred  = y_pred2
       )
print(f"Mean Absolute Error for model2: {mae}")

Mean Absolute Error for model2: 0.021873135812288724


In [122]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(
        y_true  = y_test,
        y_pred  = y_pred3
       )
print(f"Mean Absolute Error for model3: {mae}")

Mean Absolute Error for model3: 0.016901968582223106


In [123]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(
        y_true  = y_test,
        y_pred  = y_pred4
       )
print(f"Mean Absolute Error for model4: {mae}")

Mean Absolute Error for model4: 0.01829389540664148


In [149]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(
        y_true  = y_test,
        y_pred  = y_pred5
       )
print(f"Mean Absolute Error for model5: {mae}")

Mean Absolute Error for model5: 0.026048916285543847


In [125]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred1)

0.974547623782064

In [126]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred2)

0.9781268641877112

In [127]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred3)

0.9830980314177769

In [128]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred4)

0.9817061045933585

In [129]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred5)

0.9739510837144562

In [130]:
from sklearn.metrics import confusion_matrix

confusion_matrix1 = confusion_matrix(y_test, y_pred1)
confusion_matrix1

array([[4977,  118],
       [ 138, 4825]])

In [131]:
from sklearn.metrics import confusion_matrix

confusion_matrix2 = confusion_matrix(y_test, y_pred2)
confusion_matrix2

array([[5010,   85],
       [ 135, 4828]])

In [132]:
from sklearn.metrics import confusion_matrix

confusion_matrix3 = confusion_matrix(y_test, y_pred3)
confusion_matrix3

array([[5011,   84],
       [  86, 4877]])

In [133]:
from sklearn.metrics import confusion_matrix

confusion_matrix4 = confusion_matrix(y_test, y_pred4)
confusion_matrix4

array([[5003,   92],
       [  92, 4871]])

In [134]:
from sklearn.metrics import confusion_matrix

confusion_matrix5 = confusion_matrix(y_test, y_pred5)
confusion_matrix5

array([[4973,  122],
       [ 140, 4823]])

# Summary

In [193]:
#Accuracy & Confusion Matrix

from tabulate import tabulate
mydata = [
    ['Model', 'Accuracy', 'Confusion Matrix'],
      ['model1', accuracy_score(y_test, y_pred1), confusion_matrix1],
      ['model2', accuracy_score(y_test, y_pred2), confusion_matrix2],
      ['model3', accuracy_score(y_test, y_pred3), confusion_matrix3],
      ['model4', accuracy_score(y_test, y_pred4), confusion_matrix4],
      ['model5', accuracy_score(y_test, y_pred5), confusion_matrix5],
]
print(tabulate(mydata, tablefmt="grid"))

+--------+--------------------+------------------+
| Model  | Accuracy           | Confusion Matrix |
+--------+--------------------+------------------+
| model1 | 0.974547623782064  | [[4977  118]     |
|        |                    |  [ 138 4825]]    |
+--------+--------------------+------------------+
| model2 | 0.9781268641877112 | [[5010   85]     |
|        |                    |  [ 135 4828]]    |
+--------+--------------------+------------------+
| model3 | 0.9830980314177769 | [[5011   84]     |
|        |                    |  [  86 4877]]    |
+--------+--------------------+------------------+
| model4 | 0.9817061045933585 | [[5003   92]     |
|        |                    |  [  92 4871]]    |
+--------+--------------------+------------------+
| model5 | 0.9739510837144562 | [[4973  122]     |
|        |                    |  [ 140 4823]]    |
+--------+--------------------+------------------+


# Best model so far: model3
model3 = MLPClassifier( \
&emsp;    activation='tanh', \
&emsp;    solver='adam', \
&emsp;    alpha=1e-5, \
&emsp;    hidden_layer_sizes=(5, 5, 5, 5, 5), \
&emsp;    random_state=123) \
\
model3.fit(X_train, y_train) \
scores3 = cross_val_score( \
&emsp;    model3, \
&emsp;    X_train, \
&emsp;    y_train, \
&emsp;    cv=5, \
&emsp;    scoring='neg_mean_absolute_error') 
    

# Hyper-parameter variation

In [195]:
model3B = MLPClassifier(activation = 'tanh',solver = 'adam', alpha = 1e-5,hidden_layer_sizes = (5, 5, 5, 5, 5), random_state = 123
    , n_iter_no_change = 15) #Variation
model3B.fit(X_train, y_train)
scores3B = cross_val_score(model3B, X_train, y_train, cv=5, scoring='neg_mean_absolute_error')
print(scores3B)
scores3B.mean()

[-0.02174994 -0.02137708 -0.0195128  -0.01988813 -0.01889372]


-0.02028433462222426

In [196]:
model3C = MLPClassifier(activation = 'tanh',solver = 'adam', alpha = 1e-5,hidden_layer_sizes = (5, 5, 5, 5, 5), random_state = 123
    , n_iter_no_change = 20) #Variation
model3C.fit(X_train, y_train)
scores3C = cross_val_score(model3C, X_train, y_train, cv=5, scoring='neg_mean_absolute_error')
print(scores3C)
scores3C.mean()

/home/diegoflm/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[-0.02150137 -0.02100423 -0.01926423 -0.02063393 -0.01901802]


-0.02028435625050305

In [197]:
y_pred3B = model3B.predict(X_test)  
y_pred3B

array([1, 2, 1, ..., 2, 1, 1])

In [198]:
y_pred3C = model3C.predict(X_test)  
y_pred3C

array([1, 2, 1, ..., 2, 1, 1])

In [199]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(
        y_true  = y_test,
        y_pred  = y_pred3B
       )
print(f"Mean Absolute Error for model3B: {mae}")

Mean Absolute Error for model3B: 0.015510041757804733


In [200]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(
        y_true  = y_test,
        y_pred  = y_pred3C
       )
print(f"Mean Absolute Error for model3C: {mae}")

Mean Absolute Error for model3C: 0.01580831179160867


In [201]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred3B)

0.9844899582421953

In [202]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred3C)

0.9841916882083913

In [203]:
from sklearn.metrics import confusion_matrix

confusion_matrix3B = confusion_matrix(y_test, y_pred3B)
confusion_matrix3B

array([[5021,   74],
       [  82, 4881]])

In [204]:
from sklearn.metrics import confusion_matrix

confusion_matrix3C = confusion_matrix(y_test, y_pred3C)
confusion_matrix3C

array([[5026,   69],
       [  90, 4873]])

# Comparison

In [209]:
from tabulate import tabulate
mydata = [
    ['Model', 'n_iter_no_change', 'Accuracy', 'Confusion Matrix'],
      ['model3', 10, accuracy_score(y_test, y_pred3), confusion_matrix3],
      ['model3B', 15, accuracy_score(y_test, y_pred3B), confusion_matrix3B],
      ['model3C', 20, accuracy_score(y_test, y_pred3C), confusion_matrix3C]
]
print(tabulate(mydata, tablefmt="grid"))

+---------+------------------+--------------------+------------------+
| Model   | n_iter_no_change | Accuracy           | Confusion Matrix |
+---------+------------------+--------------------+------------------+
| model3  | 10               | 0.9830980314177769 | [[5011   84]     |
|         |                  |                    |  [  86 4877]]    |
+---------+------------------+--------------------+------------------+
| model3B | 15               | 0.9844899582421953 | [[5021   74]     |
|         |                  |                    |  [  82 4881]]    |
+---------+------------------+--------------------+------------------+
| model3C | 20               | 0.9841916882083913 | [[5026   69]     |
|         |                  |                    |  [  90 4873]]    |
+---------+------------------+--------------------+------------------+


# Analysis
For the model3, two variations for an hyper-parameter were done. The chosen parameter was n_iter_no_change.  
The default value for this parameter (the value for model3) is: 10  
The description for this hyper-parameter is:
"Maximum number of epochs to not meet tol improvement.  
Only effective when solver=’sgd’ or ‘adam’."  

A greater value for this parameter leads to a greatest amount of epochs, which could mean a better performance.  
The results show that a bigger value for n_iter_no_change than 10 improves the accuracy,  
but the value with the better performance is n_iter_no_change = 15.

This is a bit counterintuitive, but it could mean that a value of 20 leads the model to be a bit overfit.  
In any case, with either a value of 15 or 20, the accuracies are similar, and both are better than  
the accuracy oibtained with de default value of 10.